// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || "",
  },
  // @ts-ignore - Prisma 6.13+ supports this, but types might be lagging
  seed: {
    command: "ts-node --compiler-options '{\"module\":\"CommonJS\"}' prisma/seed.ts",
  },
});
